main: com.jothapunkt.spigot.raftcraft.RaftCraft
name: raft
version: 0.1
author: Jothapunkt
api-version: 1.21
commands:
   flotsam:
      description: Spawn flotsam
      usage: /flotsam
      permission: raftcraft.flotsam
   raft:
      description: Manage rafts
      usage: /raft
      permission: raftcraft.raft
   worlds:
      description: Manage worlds
      usage: /worlds
      permission: raftcraft.worlds
   dungeons:
      description: Manage dungeons
      usage: /dungeons
      permission: raftcraft.dungeons
   mounts:
      description: Manage mounts
      usage: /mounts
      permission: raftcraft.mounts
   skills:
      description: Manage skills
      usage: /skills
      permission: raftcraft.skills
   spawn:
      description: Spawn things
      usage: /spawn
      permission: raftcraft.spawn